import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {FaTshirt} from 'react-icons/fa'
import {GiHoodie} from 'react-icons/gi'
import { IoBeerSharp, IoExtensionPuzzleSharp } from "react-icons/io5";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ClothesWear - Clothes build for u </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div style={{'font-family':'Roboto, sans-serif'}} className="bg-hero-image md:px-32 px-10 py-24 md:bg-left-top bg-center">
        <div className="md:mb-10 mb-5">
          <p className="md:text-2xl text-lg md:mb-4 mb-2">Discover the new you</p>
          <p className="md:text-6xl text-3xl font-black capitalize font-black">Top quality clothes only</p>
        </div>
        <p className="md:text-8xl text-4xl font-black uppercase text-orange-100">Clothes Wear</p>
        <Link href={'/tshirts'}>
          <button class="text-white md:text-xl text-md bg-red-600 border-0 py-3 mt-10 px-14 focus:outline-none hover:bg-red-800 rounded-md text-lg">Buy Clothes</button>
        </Link>
      </div>

      {/* boxes */}
      <div className="h-full md:flex p-5 md:space-x-3 space-y-3 md:space-y-0">
        <div className="md:w-1/4 h-auto p-6 pb-10 pt-20 relative rounded-xl bg-gray-800">
        <FaTshirt className="absolute md:text-7xl text-9xl right-5 md:top-10 bottom-10 text-white opacity-40"/>
          <p className="text-lg text-gray-300 font-bold">Look Stylish</p>
          <p className="text-2xl text-white my-1">With</p>
          <p className="md:text-3xl text-2xl font-black uppercase text-white opacity-30">T-shirts</p>
          <Link href={'/tshirts'}>
            <button class="text-white md:text-md text-md bg-red-600 border-0 py-3 mt-5 px-9 focus:outline-none hover:bg-red-800 rounded-full text-sm">Browse</button>
          </Link>
        </div>

        <div className="md:w-1/4 h-auto p-6 pb-10 pt-20 relative rounded-xl bg-amber-500">
        <GiHoodie className="absolute md:text-8xl text-9xl right-5 md:top-10 bottom-10 text-white opacity-40"/>
          <p className="text-lg text-gray-300 font-bold">Look Stylish</p>
          <p className="text-2xl text-white my-1">With</p>
          <p className="md:text-3xl text-2xl font-black uppercase text-white opacity-30">Hoodies</p>
          <Link href={'/hoodies'}>
            <button class="text-amber-500 md:text-md text-md bg-white border-0 py-3 mt-5 px-9 focus:outline-none hover:bg-gray-100 rounded-full text-sm">Browse</button>
          </Link>
        </div>

        <div className="md:w-2/4 relative h-auto p-6 pb-10 pt-20 rounded-xl bg-red-600">
        <IoExtensionPuzzleSharp className="absolute text-9xl right-5 bottom-10 text-gray-100 opacity-70"/>
          <p className="text-lg text-gray-300 font-bold">Look Stylish</p>
          <p className="text-2xl text-white my-1">With</p>
          <p className="md:text-3xl text-2xl font-black uppercase text-white opacity-30">Stickers</p>
          <Link href={'/stickers'}>
            <button class="text-red-600 md:text-md text-md bg-white border-0 py-3 mt-5 px-9 focus:outline-none hover:bg-gray-100 rounded-full text-sm">Browse</button>
          </Link>
        </div>
      </div>

      <div className="h-full md:flex p-5 pt-0 md:space-x-3 space-y-3 md:space-y-0">
        
      <div className="md:w-2/4 relative h-auto p-6 pb-10 pt-20 rounded-xl bg-gray-300">
        <IoBeerSharp className="absolute text-9xl right-10 bottom-10"/>
          <p className="text-lg text-black font-bold">Look Stylish</p>
          <p className="text-2xl text-black my-1">With</p>
          <p className="md:text-3xl text-2xl font-black uppercase text-white opacity-80">Mugs</p>
          <Link href={'/mugs'}>
            <button class="text-gray-300 md:text-md text-md bg-black border-0 py-3 mt-5 px-9 focus:outline-none hover:bg-gray-800 rounded-full text-sm">Browse</button>
          </Link>
        </div>
        
        <div className="md:w-1/4 h-auto p-6 pb-10 relative pt-20 rounded-xl bg-green-500">
        <FaTshirt className="absolute md:text-7xl text-9xl right-5 md:top-10 bottom-10 text-white opacity-40"/>
          <p className="text-lg text-white">Look Stylish</p>
          <p className="text-2xl text-white my-1">With</p>
          <p className="md:text-3xl text-2xl font-black uppercase text-white opacity-30">T-shirts</p>
          <Link href={'/tshirts'}>
            <button class="text-green-500 md:text-md text-md bg-white border-0 py-3 mt-5 px-9 focus:outline-none hover:bg-gray-200 rounded-full text-sm">Browse</button>
          </Link>
        </div>

        <div className="md:w-1/4 relative h-auto p-6 pb-10 pt-20 rounded-xl bg-blue-600">
        <FaTshirt className="absolute md:text-7xl text-9xl right-5 md:top-10 bottom-10 text-white opacity-40"/>
          <p className="text-lg text-gray-300">Look Stylish</p>
          <p className="text-2xl text-white my-1">With</p>
          <p className="md:text-3xl text-2xl font-black uppercase text-white opacity-30">T-shirts</p>
          <Link href={'/tshirts'}>
            <button class="text-blue-600 md:text-md text-md bg-white border-0 py-3 mt-5 px-9 focus:outline-none hover:bg-gray-100 rounded-full text-sm">Browse</button>
          </Link>
        </div>
      </div>
      

      {/* content boxes */}
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
              Want clothes, Why not ClothesWear??
            </h1>
            <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Inventore minus in velit ut perferendis possimus at recusandae.
            </p>
          </div>
          <div className="flex flex-wrap -m-4">
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-red-100 text-red-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                  Shooting Stars
                </h2>
                <p className="leading-relaxed text-base">
                  Fingerstache flexitarian street art 8-bit waist co, subway
                  tile poke farm.
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-red-100 text-red-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <circle cx="6" cy="6" r="3"></circle>
                    <circle cx="6" cy="18" r="3"></circle>
                    <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                  The Catalyzer
                </h2>
                <p className="leading-relaxed text-base">
                  Fingerstache flexitarian street art 8-bit waist co, subway
                  tile poke farm.
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-red-100 text-red-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                    <circle cx="12" cy="7" r="4"></circle>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                  Neptune
                </h2>
                <p className="leading-relaxed text-base">
                  Fingerstache flexitarian street art 8-bit waist co, subway
                  tile poke farm.
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-red-100 text-red-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1zM4 22v-7"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                  Melanchole
                </h2>
                <p className="leading-relaxed text-base">
                  Fingerstache flexitarian street art 8-bit waist co, subway
                  tile poke farm.
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-red-100 text-red-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                  Bunker
                </h2>
                <p className="leading-relaxed text-base">
                  Fingerstache flexitarian street art 8-bit waist co, subway
                  tile poke farm.
                </p>
              </div>
            </div>
            <div className="xl:w-1/3 md:w-1/2 p-4">
              <div className="border border-gray-200 p-6 rounded-lg">
                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-red-100 text-red-500 mb-4">
                  <svg
                    fill="none"
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    className="w-6 h-6"
                    viewBox="0 0 24 24"
                  >
                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                  </svg>
                </div>
                <h2 className="text-lg text-gray-900 font-medium title-font mb-2">
                  Ramona Falls
                </h2>
                <p className="leading-relaxed text-base">
                  Fingerstache flexitarian street art 8-bit waist co, subway
                  tile poke farm.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
}
