import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ClothesWear - Clothes build for u </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>
      <div>
        <img src="/main-head.jpg" width alt="" />
      </div>
      <Footer/>
    </div>
  )
}
