import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ClothesWear - Clothes build for u </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="mx-auto w-4/5 mt-10">
      <h1 className="text-3xl font-bold">
        Hello world!
      </h1>
    </div>
    </div>
  )
}
